import { FlatCompat } from '@eslint/eslintrc';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const compat = new FlatCompat({ baseDirectory: path.dirname(fileURLToPath(import.meta.url)) });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: ['node_modules/**', '.next/**', 'coverage/**', 'dist/**', 'image-search/**', 'next-env.d.ts', 'public/draco/**'], // next-env.d.ts is generated by Next.js; public/draco is vendored three.js decoder code,
  },
];

export default eslintConfig;
